spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  # アプリケーション起動時にデータベースを初期化しないようにする
  jpa:
    hibernate:
      ddl-auto: update
# sqllog
logging:
  level:
    sql: debug